server:
  error:
    include-stacktrace: never
  port: 8083
spring:
  profiles:
    active: dev
  jackson:
    locale: pt_BR
    time-zone: America/Fortaleza
    serialization:
      INDENT_OUTPUT: true
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
