server:
  error:
    include-stacktrace: never
  port: 8083
spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost/transactions
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
