spring:
  datasource:
    url: jdbc:postgresql://localhost/transactions?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Fortaleza&allowPublicKeyRetrieval=true
    username: postgres
    password: postgres
    platform: postgres
    initialize: true
    initialization-mode: always
    continue-on-error: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect